### ISSUE TITLE
Creation link-block with social image

### ISSUE THREAD

**Issue by B10-Max** [GrapesJS/preset-newsletter#54] opened 2018-11-12 15:02 UTC
I used the plugin-social but it does not work well because the images of the various social is a fontawesome, in the various email clients does not work, the images are not displayed. What would be the way to make a link-block with the images of the main social networks?

Thanks in advance

**Comment by artf** [comment] 2023-06-09 09:37
Closing as the issue is related to another plugin

**Closed by artf** 2023-06-09 09:37 UTC
